# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime, date

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 558)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #f9fafb;")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 110, 211, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("background-color: white;")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(156, 170, 231, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("""
                                    background-color: #374151;
                                    color: white;
                                    font-weight: bold;
                                    border-radius: 3px;
                                    padding: 5px;
                                """)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 350, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("""
                                        background-color: #991b1b;
                                        color: white;
                                        font-weight: bold;
                                        font-size: 10px;
                                        border-radius: 3px;
                                        padding: 0px;
                                    """)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 110, 131, 19))
        self.label.setObjectName("label")
        self.label.setStyleSheet("""
                                    font-size: 16px;
                                    color: black;
                                    """)

        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(150, 10, 315, 26))
        self.labelTitle.setIndent(-1)
        self.labelTitle.setObjectName("labelTitle")
        self.labelTitle.setStyleSheet("""
                                    font-size: 20px;
                                    font-weight: bold;
                                    color: black;
                                    """)

        self.labelNama = QtWidgets.QLabel(self.centralwidget)
        self.labelNama.setGeometry(QtCore.QRect(43, 39, 330, 19))
        self.labelNama.setObjectName("labelNama")
        self.labelNama.setStyleSheet("""
                                    font-size: 16px;
                                    color: black;
                                    """)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(11, 140, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("""
                                    font-size: 13px;
                                    color: black;
                                    """)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("""
                                    font-size: 16px;
                                    color: black;
                                    """)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 205, 100, 20))
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet("""
                                    font-size: 16px;
                                    color: black;
                                    """)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 350, 135, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("""
                                        background-color: #1e3a8a;
                                        color: white;
                                        font-weight: bold;
                                        font-size: 10px;
                                        border-radius: 3px;
                                        padding: 0px;
                                    """)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 395, 157, 19))
        self.label_6.setObjectName("label_6")
        self.label_6.setStyleSheet("""
                                    font-size: 16px;
                                    color: black;
                                    """)

        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 420, 381, 111))
        self.listView.setObjectName("listView")
        self.model_riwayat = QtGui.QStandardItemModel(self.listView)
        self.listView.setModel(self.model_riwayat)

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 80, 211, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems([
            "-",
            "Pemrograman Visual",
            "Pemrograman Bergerak",
            "Pemodelan dan Simulasi",
            "Logika Fuzzy",
            "Internet Of Things"
        ])
        self.comboBox.setStyleSheet("background-color: white;")

        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(10, 230, 381, 111))
        self.listView_2.setObjectName("listView_2")
        self.model = QtGui.QStandardItemModel(self.listView_2) 
        self.listView_2.setModel(self.model)

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(160, 140, 211, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setStyleSheet("background-color: white;")

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.tambah_tugas)
        self.pushButton_2.clicked.connect(self.hapus_semua_tugas)
        self.pushButton_3.clicked.connect(self.hapus_tugas_selesai)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplikasi to-do list"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Masukkan nama tugas"))
        self.pushButton.setText(_translate("MainWindow", "(+) Tambah Tugas"))
        self.pushButton_2.setText(_translate("MainWindow", "(-) Hapus Semua Daftar Tugas"))
        self.label.setText(_translate("MainWindow", "Nama Tugas :"))
        self.labelTitle.setText(_translate("MainWindow", "KampusList"))
        self.labelNama.setText(_translate("MainWindow", "Nama: Baiq Sindi Hanjani |  NIM : F1D022115"))
        self.label_2.setText(_translate("MainWindow", "Tanggal Pengumpulan :"))
        self.label_4.setText(_translate("MainWindow", "Mata Kuliah :"))
        self.label_5.setText(_translate("MainWindow", "Daftar Tugas"))
        self.pushButton_3.setText(_translate("MainWindow", "(✓) Hapus Tugas Selesai"))
        self.label_6.setText(_translate("MainWindow", "Riwayat Tugas Selesai"))

    def tambah_tugas(self):
        mata_kuliah = self.comboBox.currentText()
        nama_tugas = self.lineEdit.text().strip()
        deadline_date = self.dateEdit.date().toPyDate()
        hari_ini = date.today()

        if mata_kuliah == "-":
            QtWidgets.QMessageBox.warning(None, "Input Tidak Lengkap", "Mata kuliah harus diisi!")
            return

        if not nama_tugas:
            QtWidgets.QMessageBox.warning(None, "Input Tidak Lengkap", "Nama tugas harus diisi!")
            return

        if deadline_date < hari_ini:
            QtWidgets.QMessageBox.warning(None, "Tanggal Tidak Valid", "Perbaiki tanggal pengumpulan Anda!")
            return

        sisa_hari = (deadline_date - hari_ini).days

        if sisa_hari == 0:
            countdown = "Hari ini"
        elif sisa_hari == 1:
            countdown = "Besok"
        else:
            countdown = f"{sisa_hari} hari lagi"

        tugas = f"[{mata_kuliah}] {nama_tugas} - {countdown}"
        item = QtGui.QStandardItem(tugas)
        item.setCheckable(True)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.model.appendRow(item)

        self.lineEdit.clear()

    def hapus_semua_tugas(self):
        self.model.clear()

    def hapus_tugas_selesai(self):
        items_to_remove = []

        for i in range(self.model.rowCount()):
            item = self.model.item(i)
            if item.checkState() == QtCore.Qt.Checked:
                items_to_remove.append(i)

        for i in reversed(items_to_remove):
            item = self.model.item(i)
            self.model_riwayat.appendRow(QtGui.QStandardItem(item.text()))
            self.model.removeRow(i)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
